<script data-cfasync="false"
    src="https://templates.hibootstrap.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/js/meanmenu.min.js"></script>
<script src="/assets/js/bootstrap.bundle.min.js"></script>
<script src="/assets/js/scrollCue.min.js"></script>
<script src="/assets/js/bootstrap-datepicker.min.js"></script>
<script src="/assets/js/appear.min.js"></script>
<script src="/assets/js/odometer.min.js"></script>
<script src="/assets/js/magnific-popup.min.js"></script>
<script src="/assets/js/fancybox.min.js"></script>
<script src="/assets/js/owl.carousel.min.js"></script>
<script src="/assets/js/parallax.min.js"></script>
<script src="/assets/js/ajaxchimp.min.js"></script>
<script src="/assets/js/form-validator.min.js"></script>
<script src="/assets/js/subscribe-custom.js"></script>
<script src="/assets/js/contact-form-script.js"></script>
<script src="/assets/js/main.js"></script>